"""add password

Revision ID: 2c8cce8e055f
Revises: 1cae280ffca1
Create Date: 2026-01-10 15:53:42.616349

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2c8cce8e055f"
down_revision = "1cae280ffca1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password", existing_type=mysql.VARCHAR(length=120), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password", existing_type=mysql.VARCHAR(length=120), nullable=True
        )

    # ### end Alembic commands ###
